name: personal_scheduler_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  firebase_storage: ^12.4.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.3
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  get_it:
  injectable:
  freezed_annotation: ^2.4.4
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  toastification: ^2.3.0
  file_picker: ^8.3.5
  table_calendar: ^3.2.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  sqflite: ^2.4.1
  path: ^1.9.0
  connectivity_plus: ^6.1.3
  hive:
  hive_flutter:
  uuid: ^4.5.1
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  injectable_generator:
  hive_generator:

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lottie/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
