name: personal_scheduler_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  firebase_storage: ^12.4.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.3
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  get_it:
  injectable:
  freezed_annotation: ^2.4.4
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  toastification: ^2.3.0
  file_picker: ^8.3.5
  table_calendar: ^3.2.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  connectivity_plus: ^6.1.3
  hive:
  hive_flutter:
  uuid: ^4.5.1
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  injectable_generator:
  hive_generator:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/icons/
